repos:
  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: pylint
        args: [influx_logging_handler]
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest
        types: [python]
        pass_filenames: false
      - id: bandit
        name: bandit
        stages: [commit]
        language: system
        entry: bandit --ini .banditrc -r
        types: [python]
        pass_filenames: false
      - id: safety
        name: safety
        entry: safety
        args:
          [check, --full-report, -r, requirements.txt, -r, requirements-dev.txt]
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: mypy
        types: [python]
        pass_filenames: false
